version: '3'
services:
  app:
    build:
      context: ../
      dockerfile: sample/Dockerfile
    command: bin/rails server --binding 0.0.0.0 --port 3000
    depends_on:
      - db
    volumes:
      - /app/node_modules
    ports:
      - "9000:3000"
  db:
    image: postgres:13.2
    environment:
      POSTGRES_PASSWORD: pgpassword
