# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 3.0
          - 3.1
          - 3.2
        gemfile:
          - gemfiles/rails_60.gemfile
          - gemfiles/rails_70.gemfile
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    - name: Set up Ruby
      uses: ruby/setup-ruby@1a615958ad9d422dd932dc1d5823942ee002799f # v1.227.0
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install --gemfile=${{ matrix.gemfile }}
    - name: Run tests and Print coverage
      env:
        COVERAGE: 1
        LOGLEVEL: info
      run: bundle exec --gemfile=${{ matrix.gemfile }} rake
